"""Add can_manage_users column to users table

Revision ID: 541a5e112cfa
Revises: 98e888f0e5af
Create Date: 2025-11-21 06:22:35.129169

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "541a5e112cfa"
down_revision = "98e888f0e5af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "can_manage_users",
                sa.Boolean(),
                nullable=False,
                server_default="0",
                comment="ユーザー管理権限",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("can_manage_users")

    # ### end Alembic commands ###
