"""create settlement_history table

Revision ID: 596dda9b64c1
Revises: 0be6e45b83bf
Create Date: 2025-11-22 14:25:38.573218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596dda9b64c1'
down_revision = '0be6e45b83bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False, comment='精算対象年'),
    sa.Column('month', sa.Integer(), nullable=False, comment='精算対象月'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='ファイル名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='ファイル保存パス'),
    sa.Column('file_format', sa.String(length=10), nullable=False, comment='ファイル形式'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='発行日時'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_history', schema=None) as batch_op:
        batch_op.create_index('idx_settlement_history_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_settlement_history_year_month', ['year', 'month'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bank_branch'))
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_customer_name'))

    op.drop_table('customers')
    op.drop_table('transfer_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('record_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint('record_count >= 0', name=op.f('check_record_count_positive')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('bank_code', sa.VARCHAR(length=4), nullable=False),
    sa.Column('branch_code', sa.VARCHAR(length=3), nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=1), nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=7), nullable=False),
    sa.Column('transfer_amount', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint("account_type IN ('1', '2', '4')", name=op.f('check_account_type')),
    sa.CheckConstraint('LENGTH(account_number) = 7', name=op.f('check_account_number_length')),
    sa.CheckConstraint('LENGTH(bank_code) = 4', name=op.f('check_bank_code_length')),
    sa.CheckConstraint('LENGTH(branch_code) = 3', name=op.f('check_branch_code_length')),
    sa.CheckConstraint('transfer_amount >= 0', name=op.f('check_transfer_amount_positive')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_bank_branch'), ['bank_code', 'branch_code'], unique=False)

    with op.batch_alter_table('settlement_history', schema=None) as batch_op:
        batch_op.drop_index('idx_settlement_history_year_month')
        batch_op.drop_index('idx_settlement_history_created_at')

    op.drop_table('settlement_history')
    # ### end Alembic commands ###
