"""Add upload functionality

Revision ID: 59bc23c7e46b
Revises: 
Create Date: 2025-11-15 11:36:19.713630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59bc23c7e46b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False, comment='顧客名'),
    sa.Column('bank_code', sa.String(length=4), nullable=False, comment='銀行コード'),
    sa.Column('branch_code', sa.String(length=3), nullable=False, comment='支店コード'),
    sa.Column('account_type', sa.String(length=1), nullable=False, comment='口座種別'),
    sa.Column('account_number', sa.String(length=7), nullable=False, comment='口座番号'),
    sa.Column('transfer_amount', sa.Integer(), nullable=False, comment='振込金額'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='登録日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.CheckConstraint("account_type IN ('1', '2', '4')", name='check_account_type'),
    sa.CheckConstraint('LENGTH(account_number) = 7', name='check_account_number_length'),
    sa.CheckConstraint('LENGTH(bank_code) = 4', name='check_bank_code_length'),
    sa.CheckConstraint('LENGTH(branch_code) = 3', name='check_branch_code_length'),
    sa.CheckConstraint('transfer_amount >= 0', name='check_transfer_amount_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('idx_bank_branch', ['bank_code', 'branch_code'], unique=False)
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_customer_name', ['customer_name'], unique=False)

    op.create_table('transfer_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='ファイル名'),
    sa.Column('record_count', sa.Integer(), nullable=False, comment='件数'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.CheckConstraint('record_count >= 0', name='check_record_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_history', schema=None) as batch_op:
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_file_name', ['file_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_history', schema=None) as batch_op:
        batch_op.drop_index('idx_file_name')
        batch_op.drop_index('idx_created_at')

    op.drop_table('transfer_history')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('idx_customer_name')
        batch_op.drop_index('idx_created_at')
        batch_op.drop_index('idx_bank_branch')

    op.drop_table('customers')
    # ### end Alembic commands ###
