"""Initial migration for all tables

Revision ID: 5d5a66c8612d
Revises: 
Create Date: 2025-11-22 16:35:34.240878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5a66c8612d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_date', sa.String(), nullable=False, comment='売上日 (YYYY-MM-DD)'),
    sa.Column('total_sales_amount', sa.Integer(), nullable=False, comment='日次合計売上'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='集計日時'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.create_index('idx_daily_sales_date_created', ['sale_date', 'created_at'], unique=False)

    op.create_table('experience_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pos_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pos_number', sa.String(), nullable=False, comment='POSレジ番号'),
    sa.Column('sale_date', sa.String(), nullable=False, comment='売上日 (YYYY-MM-DD)'),
    sa.Column('reported_at', sa.String(), nullable=False, comment='売上レポート作成日時(YYYY-MM-DD-HH-SS)'),
    sa.Column('product_code', sa.String(), nullable=False, comment='商品コード'),
    sa.Column('product_name', sa.String(), nullable=False, comment='商品名'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Integer(), nullable=False, comment='単価'),
    sa.Column('subtotal', sa.Integer(), nullable=False, comment='合計金額 (数量 * 単価)'),
    sa.Column('total_amount', sa.Integer(), nullable=False, comment='POSレジ総合計金額'),
    sa.Column('pdf_source_file', sa.String(), nullable=True, comment='読み込み元PDFファイル名'),
    sa.Column('registration_date', sa.DateTime(), nullable=False, comment='登録日時'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_sales', schema=None) as batch_op:
        batch_op.create_index('idx_pos_sales_date', ['sale_date', 'pos_number', 'product_code'], unique=False)

    op.create_table('settlement_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False, comment='精算対象年'),
    sa.Column('month', sa.Integer(), nullable=False, comment='精算対象月'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='ファイル名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='ファイル保存パス'),
    sa.Column('file_format', sa.String(length=10), nullable=False, comment='ファイル形式'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='発行日時'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_history', schema=None) as batch_op:
        batch_op.create_index('idx_settlement_history_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_settlement_history_year_month', ['year', 'month'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False, comment='ユーザー名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス'),
    sa.Column('department', sa.String(length=50), nullable=False, comment='所属'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='ハッシュ化されたパスワード'),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False, comment='ユーザー管理権限'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='登録日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('number_of_participants', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['experience_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('users')
    with op.batch_alter_table('settlement_history', schema=None) as batch_op:
        batch_op.drop_index('idx_settlement_history_year_month')
        batch_op.drop_index('idx_settlement_history_created_at')

    op.drop_table('settlement_history')
    with op.batch_alter_table('pos_sales', schema=None) as batch_op:
        batch_op.drop_index('idx_pos_sales_date')

    op.drop_table('pos_sales')
    op.drop_table('experience_programs')
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_sales_date_created')

    op.drop_table('daily_sales')
    # ### end Alembic commands ###
