"""Create users table

Revision ID: 98e888f0e5af
Revises: c4ecfbb93930
Create Date: 2025-01-27 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "98e888f0e5af"
down_revision = "c4ecfbb93930"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False, comment="ユーザー名"),
        sa.Column("email", sa.String(length=255), nullable=False, comment="メールアドレス"),
        sa.Column("department", sa.String(length=50), nullable=False, comment="所属"),
        sa.Column(
            "hashed_password", sa.String(length=255), nullable=False, comment="ハッシュ化されたパスワード"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="登録日時"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
