"""Update indexes for pos_sales and daily_sales tables

Revision ID: c243d5c775e7
Revises: c4ecfbb93930
Create Date: 2025-01-27 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = "c243d5c775e7"
down_revision = "c4ecfbb93930"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # daily_salesテーブルの変更
    # SQLiteではunique制約を削除するにはテーブル再作成が必要
    # batch_alter_tableを使用してテーブルを再作成し、unique制約を削除する
    with op.batch_alter_table("daily_sales", schema=None) as batch_op:
        # カラム定義を変更してunique制約を削除
        # SQLiteでは、batch_alter_tableを使用するとテーブルが再作成され、
        # 新しい定義（unique制約なし）が適用される
        batch_op.alter_column("sale_date", existing_type=sa.String(), nullable=False, unique=False)
        # 複合インデックスを追加
        batch_op.create_index("idx_daily_sales_date_created", ["sale_date", "created_at"], unique=False)

    # pos_salesテーブルの変更
    with op.batch_alter_table("pos_sales", schema=None) as batch_op:
        # 既存のインデックスを削除
        batch_op.drop_index("idx_pos_sales_date")
        # 新しい複合インデックスを追加
        batch_op.create_index("idx_pos_sales_date", ["sale_date", "pos_number", "product_code"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # pos_salesテーブルのロールバック
    with op.batch_alter_table("pos_sales", schema=None) as batch_op:
        batch_op.drop_index("idx_pos_sales_date")
        batch_op.create_index("idx_pos_sales_date", ["sale_date"], unique=False)

    # daily_salesテーブルのロールバック
    with op.batch_alter_table("daily_sales", schema=None) as batch_op:
        batch_op.drop_index("idx_daily_sales_date_created")
        # unique制約を再追加（SQLiteでは自動生成インデックス名が使用される）
        batch_op.alter_column("sale_date", existing_type=sa.String(), nullable=False, unique=True)
    # ### end Alembic commands ###
