"""Create pos_sales and daily_sales tables

Revision ID: c4ecfbb93930
Revises: 
Create Date: 2025-11-14 16:50:12.058533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ecfbb93930'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_date', sa.String(), nullable=False, comment='売上日 (YYYY-MM-DD)'),
    sa.Column('total_sales_amount', sa.Integer(), nullable=False, comment='日次合計売上'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='集計日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_date')
    )
    op.create_table('pos_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pos_number', sa.String(), nullable=False, comment='POSレジ番号'),
    sa.Column('sale_date', sa.String(), nullable=False, comment='売上日 (YYYY-MM-DD)'),
    sa.Column('reported_at', sa.String(), nullable=False, comment='売上レポート作成日時(YYYY-MM-DD-HH-SS)'),
    sa.Column('product_code', sa.String(), nullable=False, comment='商品コード'),
    sa.Column('product_name', sa.String(), nullable=False, comment='商品名'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Integer(), nullable=False, comment='単価'),
    sa.Column('subtotal', sa.Integer(), nullable=False, comment='合計金額 (数量 * 単価)'),
    sa.Column('total_amount', sa.Integer(), nullable=False, comment='POSレジ総合計金額'),
    sa.Column('pdf_source_file', sa.String(), nullable=True, comment='読み込み元PDFファイル名'),
    sa.Column('registration_date', sa.DateTime(), nullable=False, comment='登録日時'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_sales', schema=None) as batch_op:
        batch_op.create_index('idx_pos_sales_date', ['sale_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_sales', schema=None) as batch_op:
        batch_op.drop_index('idx_pos_sales_date')

    op.drop_table('pos_sales')
    op.drop_table('daily_sales')
    # ### end Alembic commands ###
