"""Add reservation and program tables

Revision ID: dcaebd2ff56f
Revises: 
Create Date: 2025-11-10 22:22:18.317242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcaebd2ff56f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='プログラム名'),
    sa.Column('description', sa.Text(), nullable=True, comment='プログラム説明'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='所要時間（分）'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='定員数'),
    sa.Column('price', sa.Integer(), nullable=False, comment='料金（円）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='有効/無効フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index('idx_programs_is_active', ['is_active'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False, comment='プログラムID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='ユーザーID（ユーザーテーブル実装後に外部キー制約を追加）'),
    sa.Column('reservation_date', sa.Date(), nullable=False, comment='予約日'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='開始時間'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='終了時間'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='予約ステータス'),
    sa.Column('customer_name', sa.String(length=100), nullable=True, comment='予約者名'),
    sa.Column('customer_email', sa.String(length=255), nullable=True, comment='予約者メールアドレス'),
    sa.Column('customer_phone', sa.String(length=20), nullable=True, comment='予約者電話番号'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index('idx_reservations_date', ['reservation_date'], unique=False)
        batch_op.create_index('idx_reservations_date_status', ['reservation_date', 'status'], unique=False)
        batch_op.create_index('idx_reservations_program_id', ['program_id'], unique=False)
        batch_op.create_index('idx_reservations_status', ['status'], unique=False)
        batch_op.create_index('idx_reservations_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index('idx_reservations_user_id')
        batch_op.drop_index('idx_reservations_status')
        batch_op.drop_index('idx_reservations_program_id')
        batch_op.drop_index('idx_reservations_date_status')
        batch_op.drop_index('idx_reservations_date')

    op.drop_table('reservations')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index('idx_programs_is_active')

    op.drop_table('programs')
    # ### end Alembic commands ###
