"""Add Customer table with bank info

Revision ID: e907d7044f30
Revises: 7fda82113420
Create Date: 2025-11-22 15:17:35.567457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e907d7044f30'
down_revision = '7fda82113420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # customersテーブルが存在しない場合は作成
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_code', sa.String(length=4), nullable=False),
    sa.Column('branch_code', sa.String(length=3), nullable=False),
    sa.Column('account_type', sa.String(length=1), nullable=True),
    sa.Column('account_number', sa.String(length=7), nullable=False),
    sa.Column('transfer_amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=50), nullable=False, comment='顧客ID'))
        batch_op.add_column(sa.Column('business_name', sa.String(length=200), nullable=False, comment='事業者名'))
        batch_op.add_column(sa.Column('representative_name', sa.String(length=100), nullable=True, comment='代表者氏名'))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True, comment='郵便番号'))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True, comment='住所'))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'))
        batch_op.add_column(sa.Column('fax', sa.String(length=20), nullable=True, comment='FAX番号'))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True, comment='メールアドレス'))
        batch_op.add_column(sa.Column('contract_date', sa.Date(), nullable=True, comment='契約日'))
        batch_op.add_column(sa.Column('contract_type', sa.String(length=50), nullable=True, comment='契約区分'))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=50), nullable=True, comment='金融機関名'))
        batch_op.add_column(sa.Column('branch_name', sa.String(length=50), nullable=True, comment='支店名'))
        batch_op.add_column(sa.Column('account_holder', sa.String(length=100), nullable=False, comment='口座名義（カナ）'))
        batch_op.add_column(sa.Column('transfer_date', sa.Date(), nullable=True, comment='振込予定日'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True, comment='備考'))
        batch_op.add_column(sa.Column('staff_name', sa.String(length=100), nullable=True, comment='担当者'))
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
        batch_op.alter_column('transfer_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_customers_customer_id'), ['customer_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
