"""Add Customer table with bank info

Revision ID: e907d7044f30
Revises: merge_heads
Create Date: 2025-11-22 15:17:35.567457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e907d7044f30'
down_revision = 'merge_heads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_history')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=50), nullable=False, comment='顧客ID'))
        batch_op.add_column(sa.Column('business_name', sa.String(length=200), nullable=False, comment='事業者名'))
        batch_op.add_column(sa.Column('representative_name', sa.String(length=100), nullable=True, comment='代表者氏名'))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True, comment='郵便番号'))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True, comment='住所'))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'))
        batch_op.add_column(sa.Column('fax', sa.String(length=20), nullable=True, comment='FAX番号'))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True, comment='メールアドレス'))
        batch_op.add_column(sa.Column('contract_date', sa.Date(), nullable=True, comment='契約日'))
        batch_op.add_column(sa.Column('contract_type', sa.String(length=50), nullable=True, comment='契約区分'))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=50), nullable=True, comment='金融機関名'))
        batch_op.add_column(sa.Column('branch_name', sa.String(length=50), nullable=True, comment='支店名'))
        batch_op.add_column(sa.Column('account_holder', sa.String(length=100), nullable=False, comment='口座名義（カナ）'))
        batch_op.add_column(sa.Column('transfer_date', sa.Date(), nullable=True, comment='振込予定日'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True, comment='備考'))
        batch_op.add_column(sa.Column('staff_name', sa.String(length=100), nullable=True, comment='担当者'))
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
        batch_op.alter_column('transfer_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_bank_branch'))
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_customer_name'))
        batch_op.create_index(batch_op.f('ix_customers_customer_id'), ['customer_id'], unique=True)
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_index(batch_op.f('ix_customers_customer_id'))
        batch_op.create_index(batch_op.f('idx_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_bank_branch'), ['bank_code', 'branch_code'], unique=False)
        batch_op.alter_column('transfer_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.drop_column('staff_name')
        batch_op.drop_column('notes')
        batch_op.drop_column('transfer_date')
        batch_op.drop_column('account_holder')
        batch_op.drop_column('branch_name')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('contract_type')
        batch_op.drop_column('contract_date')
        batch_op.drop_column('email')
        batch_op.drop_column('fax')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('representative_name')
        batch_op.drop_column('business_name')
        batch_op.drop_column('customer_id')

    op.create_table('transfer_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('record_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.CheckConstraint('record_count >= 0', name=op.f('check_record_count_positive')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
